version: '3.4'

networks:
  app_network:

services:
  coachboard_fe:
    image: coachboard_fe
    build:
      context: app
      dockerfile: ./Dockerfile
      args:
        VITE_API_URL: "https://api.coachboard.az"
        VITE_MINIO_URL: "https://minio.coachboard.az"
        VITE_DEPLOY_ENV: prod
    environment:
      - NODE_ENV=production
    networks:
      - app_network
    ports:
      - "8080:92"