version: '3.4'

networks:
  app_network:

services:
  coachboard_fe:
    image: coachboard_fe
    build:
      context: app
      dockerfile: ./Dockerfile
      args:
        VITE_API_URL: "https://api.coachboard.az"
        VITE_MINIO_URL: "https://minio.coachboard.az"
        VITE_DEPLOY_ENV: prod
        VITE_UNLEASH_APIKEY: "*:production.331c4c9b2406f2fb4cf62b657789eca12b7194fcdb1ca2ef9d70538b"
    environment:
      - NODE_ENV=production
    networks:
      - app_network
    ports:
      - "8080:92"